# Generated by Django 4.2.27 on 2026-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('science', 'Science & Technology'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('motivational', 'Motivational'), ('fiction', 'Fiction'), ('biography', 'Biography')], max_length=50),
        ),
    ]
