# Generated by Django 6.0.2 on 2026-02-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_readingprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
