# Generated by Django 6.0.1 on 2026-02-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookread',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
