# Generated by Django 6.0.1 on 2026-02-28 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookread_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookRead',
        ),
    ]
