# Generated by Django 6.0.1 on 2026-03-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unlock_after_books',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
