# Generated by Django 6.0.1 on 2026-03-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_unlock_after_books_readingprogress_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='is_completed',
        ),
    ]
