# Generated by Django 6.0.2 on 2026-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_readingstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='reading_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
